# Parameters specific to data collection
collection:
  label_select: 0
  labels: ["sheep", "coke", "neither"]
  ppi_csv: "ppi_coordinates.csv"
  ppi:
    n_positions: 10
    n_rotations: 6
  object:
    n_rotations: 30
  x_min: -2
  x_max: 3
  y_min: -0.25
  y_max: 4
  n_steps: 15
  max_images:
  # Set this to True AFTER...
  # Checking all coordinates of the PenguinPi are within arena
  taking_images: True

# These parameters are used when not passing a custom parameter dictionary in automated_testing.py
# However, exp_name is still used in nn_detect.py
training:
  exp_name: 'vgg_1_3'
  init_lr: 5.0e-3
  batch_size: 256
  n_epochs: 25
  weight_decay: 1.0e-5
  num_classes: 3
  load_best: 1
  gpu_ids: '0'
  lr_scheduler:
      step_size: 1
      gamma: 0.9

# Testing, training, master
mode: "master"
