ARUCO:
  max_tvecs_norm: 15
  marker_length: 0.1

YOLO:
  FOV:
    # in radians, taken from PenguinPi.sdf
    horizontal: 1.0855
    vertical: 0.8517

  THRESHOLD:
    confidence: 0.35
    NMS: 0.2
    # Different distance thresholds
    max_distance_coke: 3
    max_distance_sheep: 3
    max_match_error: 0.2
    dupe_abs_dist: 2
    dupe_x: 0.6
    dupe_y: 0.6
    capture_window: 50

  PATH:
    weights: "yolo_cfg/custom-yolov4-tiny-detector_best.weights"
    cfg: "yolo_cfg/custom-yolov4-tiny-detector.cfg"
    classes: "yolo_cfg/obj.names"

  NETWORK_SIZE:
    small: !!python/tuple [320, 320]
    medium: !!python/tuple [416, 416]
    large: !!python/tuple [608, 608]
    custom_1: !!python/tuple [512, 512]

  DRAWING:
    colors:
      - !!python/tuple [255,51,255]
      - !!python/tuple [255, 255, 255]
      - !!python/tuple [0, 255, 0]
    font_size: 0.5
    font_thiccness: 2
    text_offset: 18
